[package]
name = "coutils"
version = "1.3.0"
edition = "2021"
description= "A set of useful functions for Rust."
homepage = "https://github.com/angeldollface/coutils"
repository = "https://github.com/angeldollface/coutils"
documentation = "https://github.com/angeldollface/coutils"
readme = "README.markdown"
keywords = [
  "utilities"
]
categories = [
  "utilities"
]
exclude = [
  "/.github"
]

[dependencies]
rand = "0.8.5"
git2 = "0.17.2"
fs_extra = "1.2.0"
file-serve = "0.2.4"