on: [push]
name: Coutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Run tests."
        uses: actions-rs/cargo@v1
        with:
          command: test
